"use client"

import type React from "react"

import { createContext, useContext, useState } from "react"

// Define available languages
const languages = ["en", "fr", "es", "de", "ru", "am"] as const
type Language = (typeof languages)[number]

// Define translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    theme: "Theme",
    logout: "Logout",
    settings: "Settings",
    edit_profile: "Edit Profile",
    close: "Close",
    display_name: "Display Name",
    status: "Status",
    bio: "Bio",
    bio_placeholder: "Write a little about yourself",
    bio_description: "Tell people about yourself in a few words",
    cancel: "Cancel",
    save_changes: "Save Changes",
    status_online: "Online",
    status_away: "Away",
    status_busy: "Busy",
    status_offline: "Offline",
    appearance: "Appearance",
    language: "Language",
    notifications: "Notifications",
    privacy: "Privacy",
    help: "Help",
    light_mode: "Light Mode",
    dark_mode: "Dark Mode",
    black_mode: "Black Mode",
    search: "Search",
    contacts: "Contacts",
    add_contact: "Add Contact",
    search_contacts: "Search contacts",
    no_contacts: "No contacts yet",
    no_contacts_found: "No contacts found",
    add_your_first_contact: "Add your first contact to start chatting",
    search_by_username_or_phone: "Search by username or phone number",
    enter_username_or_phone: "Enter username or phone number",
    search_results: "Search Results",
    no_users_found: "No users found",
    try_different_search: "Try a different search term",
    add_contact_description: "You can add contacts by searching for their username or phone number.",
    contact_added: "Contact Added",
    contact_added_description: "{name} has been added to your contacts.",
  },
  fr: {
    theme: "Thème",
    logout: "Déconnexion",
    settings: "Paramètres",
    edit_profile: "Modifier le profil",
    close: "Fermer",
    display_name: "Nom d'affichage",
    status: "Statut",
    bio: "Bio",
    bio_placeholder: "Écrivez un peu sur vous-même",
    bio_description: "Parlez de vous en quelques mots",
    cancel: "Annuler",
    save_changes: "Enregistrer les modifications",
    status_online: "En ligne",
    status_away: "Absent",
    status_busy: "Occupé",
    status_offline: "Hors ligne",
    appearance: "Apparence",
    language: "Langue",
    notifications: "Notifications",
    privacy: "Confidentialité",
    help: "Aide",
    light_mode: "Mode clair",
    dark_mode: "Mode sombre",
    black_mode: "Mode noir",
    search: "Rechercher",
    contacts: "Contacts",
    add_contact: "Ajouter un contact",
    search_contacts: "Rechercher des contacts",
    no_contacts: "Pas encore de contacts",
    no_contacts_found: "Aucun contact trouvé",
    add_your_first_contact: "Ajoutez votre premier contact pour commencer à discuter",
    search_by_username_or_phone: "Rechercher par nom d'utilisateur ou numéro de téléphone",
    enter_username_or_phone: "Entrez le nom d'utilisateur ou le numéro de téléphone",
    search_results: "Résultats de recherche",
    no_users_found: "Aucun utilisateur trouvé",
    try_different_search: "Essayez un terme de recherche différent",
    add_contact_description:
      "Vous pouvez ajouter des contacts en recherchant leur nom d'utilisateur ou numéro de téléphone.",
    contact_added: "Contact ajouté",
    contact_added_description: "{name} a été ajouté à vos contacts.",
  },
  es: {
    theme: "Tema",
    logout: "Cerrar sesión",
    settings: "Configuración",
    edit_profile: "Editar perfil",
    close: "Cerrar",
    display_name: "Nombre para mostrar",
    status: "Estado",
    bio: "Biografía",
    bio_placeholder: "Escribe un poco sobre ti",
    bio_description: "Cuéntale a la gente sobre ti en pocas palabras",
    cancel: "Cancelar",
    save_changes: "Guardar cambios",
    status_online: "En línea",
    status_away: "Ausente",
    status_busy: "Ocupado",
    status_offline: "Desconectado",
    appearance: "Apariencia",
    language: "Idioma",
    notifications: "Notificaciones",
    privacy: "Privacidad",
    help: "Ayuda",
    light_mode: "Modo claro",
    dark_mode: "Modo oscuro",
    black_mode: "Modo negro",
    search: "Buscar",
    contacts: "Contactos",
    add_contact: "Añadir contacto",
    search_contacts: "Buscar contactos",
    no_contacts: "Aún no hay contactos",
    no_contacts_found: "No se encontraron contactos",
    add_your_first_contact: "Añade tu primer contacto para empezar a chatear",
    search_by_username_or_phone: "Buscar por nombre de usuario o número de teléfono",
    enter_username_or_phone: "Introduce el nombre de usuario o número de teléfono",
    search_results: "Resultados de búsqueda",
    no_users_found: "No se encontraron usuarios",
    try_different_search: "Prueba con un término de búsqueda diferente",
    add_contact_description: "Puedes añadir contactos buscando su nombre de usuario o número de teléfono.",
    contact_added: "Contacto añadido",
    contact_added_description: "{name} ha sido añadido a tus contactos.",
  },
  de: {
    theme: "Thema",
    logout: "Abmelden",
    settings: "Einstellungen",
    edit_profile: "Profil bearbeiten",
    close: "Schließen",
    display_name: "Anzeigename",
    status: "Status",
    bio: "Bio",
    bio_placeholder: "Schreibe etwas über dich",
    bio_description: "Erzähle in wenigen Worten von dir",
    cancel: "Abbrechen",
    save_changes: "Änderungen speichern",
    status_online: "Online",
    status_away: "Abwesend",
    status_busy: "Beschäftigt",
    status_offline: "Offline",
    appearance: "Erscheinungsbild",
    language: "Sprache",
    notifications: "Benachrichtigungen",
    privacy: "Datenschutz",
    help: "Hilfe",
    light_mode: "Heller Modus",
    dark_mode: "Dunkler Modus",
    black_mode: "Schwarzer Modus",
    search: "Suchen",
    contacts: "Kontakte",
    add_contact: "Kontakt hinzufügen",
    search_contacts: "Kontakte suchen",
    no_contacts: "Noch keine Kontakte",
    no_contacts_found: "Keine Kontakte gefunden",
    add_your_first_contact: "Füge deinen ersten Kontakt hinzu, um mit dem Chatten zu beginnen",
    search_by_username_or_phone: "Nach Benutzername oder Telefonnummer suchen",
    enter_username_or_phone: "Benutzername oder Telefonnummer eingeben",
    search_results: "Suchergebnisse",
    no_users_found: "Keine Benutzer gefunden",
    try_different_search: "Versuche einen anderen Suchbegriff",
    add_contact_description:
      "Du kannst Kontakte hinzufügen, indem du nach ihrem Benutzernamen oder ihrer Telefonnummer suchst.",
    contact_added: "Kontakt hinzugefügt",
    contact_added_description: "{name} wurde zu deinen Kontakten hinzugefügt.",
  },
  ru: {
    theme: "Тема",
    logout: "Выйти",
    settings: "Настройки",
    edit_profile: "Редактировать профиль",
    close: "Закрыть",
    display_name: "Отображаемое имя",
    status: "Статус",
    bio: "О себе",
    bio_placeholder: "Напишите немного о себе",
    bio_description: "Расскажите о себе в нескольких словах",
    cancel: "Отмена",
    save_changes: "Сохранить изменения",
    status_online: "В сети",
    status_away: "Отошел",
    status_busy: "Занят",
    status_offline: "Не в сети",
    appearance: "Внешний вид",
    language: "Язык",
    notifications: "Уведомления",
    privacy: "Конфиденциальность",
    help: "Помощь",
    light_mode: "Светлый режим",
    dark_mode: "Темный режим",
    black_mode: "Черный режим",
    search: "Поиск",
    contacts: "Контакты",
    add_contact: "Добавить контакт",
    search_contacts: "Поиск контактов",
    no_contacts: "Пока нет контактов",
    no_contacts_found: "Контакты не найдены",
    add_your_first_contact: "Добавьте свой первый контакт, чтобы начать общение",
    search_by_username_or_phone: "Поиск по имени пользователя или номеру телефона",
    enter_username_or_phone: "Введите имя пользователя или номер телефона",
    search_results: "Результаты поиска",
    no_users_found: "Пользователи не найдены",
    try_different_search: "Попробуйте другой поисковый запрос",
    add_contact_description: "Вы можете добавлять контакты, выполняя поиск по имени пользователя или номеру телефона.",
    contact_added: "Контакт добавлен",
    contact_added_description: "{name} добавлен в ваши контакты.",
  },
  am: {
    theme: "ገጽታ",
    logout: "ውጣ",
    settings: "ቅንብሮች",
    edit_profile: "መገለጫ አስተካክል",
    close: "ዝጋ",
    display_name: "የሚታይ ስም",
    status: "ሁኔታ",
    bio: "ባዮግራፊ",
    bio_placeholder: "ስለራስህ ጥቂት ጻፍ",
    bio_description: "ስለራስህ በጥቂት ቃላት ንገር",
    cancel: "ሰርዝ",
    save_changes: "ለውጦችን አስቀምጥ",
    status_online: "መስመር ላይ",
    status_away: "ርቆ",
    status_busy: "ተጠምዷል",
    status_offline: "ከመስመር ውጪ",
    appearance: "መልክ",
    language: "ቋንቋ",
    notifications: "ማሳወቂያዎች",
    privacy: "ግላዊነት",
    help: "እገዛ",
    light_mode: "ብሩህ ሁነታ",
    dark_mode: "ጨለማ ሁነታ",
    black_mode: "ጥቁር ሁነታ",
    search: "ፈልግ",
    contacts: "ዝርዝሮች",
    add_contact: "ዝርዝር አክል",
    search_contacts: "ዝርዝሮችን ፈልግ",
    no_contacts: "እስካሁን ምንም ዝርዝሮች የሉም",
    no_contacts_found: "ምንም ዝርዝሮች አልተገኙም",
    add_your_first_contact: "መወያየት ለመጀመር የመጀመሪያ ዝርዝርዎን ያክሉ",
    search_by_username_or_phone: "በተጠቃሚ ስም ወይም ስልክ ቁጥር ፈልግ",
    enter_username_or_phone: "የተጠቃሚ ስም ወይም ስልክ ቁጥር አስገባ",
    search_results: "የፍለጋ ውጤቶች",
    no_users_found: "ምንም ተጠቃሚዎች አልተገኙም",
    try_different_search: "የተለየ የፍለጋ ቃል ይሞክሩ",
    add_contact_description: "በተጠቃሚ ስም ወይም ስልክ ቁጥር በመፈለግ ዝርዝሮችን ማከል ይችላሉ።",
    contact_added: "ዝርዝር ታክሏል",
    contact_added_description: "{name} ወደ ዝርዝሮችዎ ታክሏል።",
  },
}

// Create context
type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Make sure the context is properly initialized
const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Create provider
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

// Create hook
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
